version: "3"
services:
  bob-agent:
    image: bcgovimages/aries-cloudagent:py36-1.14-1_0.5.1
    ports:
      - ${BOB_HTTP_PORT}:${BOB_HTTP_PORT}
      - ${BOB_ADMIN_PORT}:${BOB_ADMIN_PORT}
    entrypoint: /bin/bash
    command: [
        "-c",
        "
          aca-py start \
          --inbound-transport http '0.0.0.0' ${BOB_HTTP_PORT} \
          --outbound-transport http \
          --endpoint ${BOB_AGENT_ENDPOINT} \
          --webhook-url ${BOB_WEBHOOK_URL} \
          --wallet-type 'indy' \
          --seed '${BOB_WALLET_SEED}' \
          --admin '0.0.0.0' ${BOB_ADMIN_PORT} \
          --admin-insecure-mode \
          --log-level info \
          --label ${BOB_AGENT_NAME}",
        ]
  alice-agent:
    image: bcgovimages/aries-cloudagent:py36-1.14-1_0.5.1
    ports:
      - ${ALICE_HTTP_PORT}:${ALICE_HTTP_PORT}
      - ${ALICE_ADMIN_PORT}:${ALICE_ADMIN_PORT}
    entrypoint: /bin/bash
    command: [
      "-c",
      "aca-py start \
      --inbound-transport http '0.0.0.0' ${ALICE_HTTP_PORT} \
      --outbound-transport http \
      --endpoint ${ALICE_AGENT_ENDPOINT} \
      --webhook-url ${ALICE_WEBHOOK_URL} \
      --wallet-type 'indy' \
      --seed '${ALICE_WALLET_SEED}' \
      --admin '0.0.0.0' ${ALICE_ADMIN_PORT} \
      --admin-insecure-mode \
      --log-level info \
      --label ${ALICE_AGENT_NAME}",
    ]
  alice-notebook:
    build:
      context: .
      args:
        - jupyter_port=${ALICE_JUPYTER_PORT}
    depends_on:
      - alice-agent
    volumes:
      - ./demo/alice:/workspace
    ports:
      - "8888:8888"
      - ${ALICE_WEBHOOK_PORT}:${ALICE_WEBHOOK_PORT}
  bob-notebook:
    build:
      context: .
      args:
        - jupyter_port=${BOB_JUPYTER_PORT}
    depends_on:
      - bob-agent
    volumes:
      - ./demo/bob:/workspace
    ports:
      - "8889:8888"
      - ${BOB_WEBHOOK_PORT}:${BOB_WEBHOOK_PORT}